import type { RoadmapPanel } from "@/lib/types";

// Every word x/y is inside the middle 50% box (25–75) so the whole
// composition stays focused in the center like a diagnostic scan.
// Word order within each panel is also the connector's reading order.
export const roadmapConfig: RoadmapPanel[] = [
  {
    id: "intro",
    kind: "statement",
    theme: "intro",
    background: null,
    focalPoint: "center center",
    overlay: "",
    words: [],
    statement: "Your health doesn't move\nin straight lines.",
  },
  {
    id: "blue-1",
    kind: "scatter",
    theme: "blue",
    background: "/blue1.jpg",
    focalPoint: "center 25%",
    overlay: "bg-black/30",
    words: [
      { id: "b1-your", text: "your", x: 30, y: 34 },
      { id: "b1-body", text: "body", x: 34, y: 52 },
      { id: "b1-is", text: "is", x: 50, y: 54 },
      { id: "b1-talking", text: "talking", x: 66, y: 50 },
      { id: "b1-every", text: "every", x: 68, y: 66 },
      { id: "b1-where", text: "where", x: 48, y: 66 },
    ],
  },
  {
    id: "blue-2",
    kind: "scatter",
    theme: "blue",
    background: "/blue2.jpg",
    focalPoint: "center center",
    overlay: "bg-black/40",
    words: [
      { id: "b2-but-most", text: "BUT MOST", x: 64, y: 32 },
      { id: "b2-health-systems", text: "HEALTH SYSTEMS", x: 50, y: 50 },
      { id: "b2-arent-listening", text: "AREN'T LISTENING", x: 32, y: 68 },
    ],
  },
  {
    id: "blue-3",
    kind: "scatter",
    theme: "blue",
    background: "/blue3.jpg",
    focalPoint: "center center",
    overlay: "bg-black/25",
    words: [
      { id: "b3-every", text: "every", x: 30, y: 34 },
      { id: "b3-insight", text: "insight", x: 54, y: 32 },
      { id: "b3-informed", text: "informed", x: 32, y: 50 },
      { id: "b3-by", text: "by", x: 50, y: 52 },
      { id: "b3-what", text: "what", x: 70, y: 50 },
      { id: "b3-comes", text: "comes", x: 40, y: 68 },
      { id: "b3-next", text: "next", x: 64, y: 68 },
    ],
  },
  {
    id: "orange-1",
    kind: "scatter",
    theme: "orange",
    background: "/orange1.jpg",
    focalPoint: "center 40%",
    overlay: "bg-black/30",
    words: [
      { id: "o1-patterns", text: "patterns", x: 32, y: 34 },
      { id: "o1-signals", text: "signals", x: 66, y: 34 },
      { id: "o1-insight", text: "INSIGHT", x: 50, y: 52 },
      { id: "o1-your-data", text: "your data", x: 50, y: 68 },
    ],
  },
  {
    id: "orange-2",
    kind: "scatter",
    theme: "orange",
    background: "/orange2.jpg",
    focalPoint: "center 30%",
    overlay: "bg-black/35",
    words: [
      { id: "o2-turning", text: "turning", x: 32, y: 36 },
      { id: "o2-noise", text: "noise", x: 64, y: 46 },
      { id: "o2-into", text: "into", x: 38, y: 58 },
      { id: "o2-knowing", text: "knowing", x: 66, y: 68 },
    ],
  },
  {
    id: "orange-3",
    kind: "scatter",
    theme: "orange",
    background: "/orange3.jpg",
    focalPoint: "center 25%",
    overlay: "bg-black/45",
    words: [
      { id: "o3-action", text: "ACTION", x: 36, y: 40 },
      { id: "o3-follows", text: "follows", x: 58, y: 52 },
      { id: "o3-understanding", text: "understanding", x: 48, y: 66 },
    ],
  },
  {
    id: "orange-4",
    kind: "statement",
    theme: "orange",
    background: "/orange4.jpg",
    focalPoint: "center center",
    overlay: "bg-black/40",
    words: [],
    statement: "and the ring stays quiet,\nuntil it matters.",
  },
];
